name: flash_chat
description: A new Flutter application.

version: 2.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  firebase_core: ^2.4.0
  firebase_auth: ^4.1.1
  cloud_firestore: ^4.0.4
  flutter_contacts: ^1.1.5+1
  provider: ^6.0.4
  #modal_progress_hud: ^0.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
